# Generated by Django 5.1.15 on 2026-07-09 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Категория FAQ', 'verbose_name_plural': 'Категории FAQ'},
        ),
        migrations.AlterModelOptions(
            name='faqitem',
            options={'ordering': ['order', 'question'], 'verbose_name': 'Вопрос-Ответ FAQ', 'verbose_name_plural': 'Вопросы-Ответы FAQ'},
        ),
        migrations.AddField(
            model_name='faqitem',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок внутри категории'),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='faq.faqcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='question',
            field=models.CharField(max_length=255, verbose_name='Вопрос'),
        ),
    ]
