# Generated by Django 5.1.15 on 2026-07-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='img',
        ),
    ]
