# Generated by Django 5.1.15 on 2026-07-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_remove_teacher_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='age',
        ),
        migrations.AddField(
            model_name='teacher',
            name='achievments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(default='static/img/teachers/teacher_placeholder.png', upload_to='teachers/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='short_info',
            field=models.CharField(default='', max_length=250),
        ),
    ]
