# Generated by Django 6.0.6 on 2026-07-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_rename_name_teacher_first_name_remove_teacher_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
