# Generated by Django 5.2.15 on 2026-07-08 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_teacherfeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherfeedback',
            old_name='text',
            new_name='question',
        ),
    ]
