# Generated by Django 5.1.15 on 2026-07-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('event_name', models.CharField(max_length=150)),
                ('short_description', models.CharField(max_length=255)),
                ('detailed_description', models.TextField()),
            ],
        ),
    ]
