# Generated by Django 6.0.7 on 2026-07-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название курса')),
                ('short_description', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('icon', models.CharField(default='📚', max_length=50, verbose_name='Эмодзи-иконка')),
                ('teachers', models.ManyToManyField(related_name='courses', to='teachers.teacher', verbose_name='Преподаватели')),
            ],
            options={
                'verbose_name': 'Учебный курс',
                'verbose_name_plural': 'Учебные курсы',
            },
        ),
    ]
