# Generated by Django 6.0.6 on 2026-07-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolapplication',
            name='achievements',
            field=models.ImageField(upload_to='achievements/'),
        ),
    ]
